name: Build spilo image
on:

  workflow_dispatch:
   inputs:
    task_name: 
     description : spilo_test
     default : "spilo"
     type: "string"
  
jobs:

 job1:
 runs-on : ubuntu-latest
      - name: task inside job1
        run: |
          echo The task_name is ${{ inputs.task_name }}
          
job2:
 runs-on : ubuntu-latest
   steps:
      - uses: actions/checkout@v3
          with:
          repository: 17Vivek17/spilo
          ref: 3.0-p1 
