name: Build spilo image
on:

  workflow_dispatch:
  inputs:
  task_name: spilo_repo
  description : spilo_test
  default : spilo
  type: string
  
  
jobs:

 job1:
 runs on : ubuntu-latest
    steps:
      - name: task inside job1
        run: |
          echo The task_name is ${{ inputs.task_name }}

